#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Taint-Util
Version  : 0.08
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/A/AV/AVAR/Taint-Util-0.08.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AV/AVAR/Taint-Util-0.08.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtaint-util-perl/libtaint-util-perl_0.08-3.debian.tar.xz
Summary  : 'Test for and flip the taint flag without regex matches or C<eval>'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Taint-Util-lib
Requires: perl-Taint-Util-license
Requires: perl-Taint-Util-man

%description
NAME
Taint::Util - Test for and flip the taint flag without regex matches or
"eval"

%package lib
Summary: lib components for the perl-Taint-Util package.
Group: Libraries
Requires: perl-Taint-Util-license

%description lib
lib components for the perl-Taint-Util package.


%package license
Summary: license components for the perl-Taint-Util package.
Group: Default

%description license
license components for the perl-Taint-Util package.


%package man
Summary: man components for the perl-Taint-Util package.
Group: Default

%description man
man components for the perl-Taint-Util package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Taint-Util-0.08
mkdir -p %{_topdir}/BUILD/Taint-Util-0.08/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Taint-Util-0.08/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Taint-Util
cp LICENSE %{buildroot}/usr/share/doc/perl-Taint-Util/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Taint/Util.pm

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/Taint/Util/Util.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Taint-Util/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Taint::Util.3
